### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by sxphamari** [PokeSerGG/poke_rpchat#1]
Only 1 doctor and 1 police can see the alert.

**Comment by PokeSer** [comment]
Hello! I need you to reproduce the error for me, in the event that it is so, they have never reported that to me and it has been more than 1 year. Give me screenshots or a video of the bug and I'll look at it.

**Comment by sxphamari** [comment]
There are no errors but i really dont know why only 1 doctor and 1 police only can receive it im using it on vorp framework.

**Comment by PokeSer** [comment]
vorp lua or csharp?

**Comment by sxphamari** [comment]
lua

**Comment by PokeSer** [comment]
I have to see if something has changed, because when I made this script there was only vorp c#

**Comment by sxphamari** [comment]
Ohh i see

**Comment by sxphamari** [comment]
Ill just wait for an update.

**Comment by PokeSer** [comment]
Well, after a few days that I have installed redm again, I have tried it and it does not give me any errors and everything works correctly. Are you using Onesync on?

**Comment by PokeSer** [comment]
The bug could not be repro
