### ISSUE TITLE
Error en consola

### ISSUE THREAD

**Issue by dkdue** [PokeSerGG/poke_rpchat#2]
Hola Poke, igual no te acuerdas de mí pero yo si que me acuerdo de Vorp y todo lo que habéis creado, soy kessef,
bueno simplemente quería saludar y decirte que tengo un error con tu script rpchat:

`[    c-scripting-core] Creating script environments for poke_rpchat
[  script:poke_rpchat] Error loading script server/admin.lua in resource poke_rpchat: citizen:/scripting/lua/scheduler.lua:867: No such export vorpAPI in resource vorp_core
[  script:poke_rpchat] stack traceback:
[  script:poke_rpchat] 	[C]: in function 'error'
[  script:poke_rpchat] 	citizen:/scripting/lua/scheduler.lua:867: in metamethod '__index'
[  script:poke_rpchat] 	@poke_rpchat/server/admin.lua:1: in main chunk
[    c-scripting-core] Failed to load script server/admin.lua.
[ citizen-server-impl] Started resource poke_rpchat`

Uso vorp core lua, supongo que tu script está creado para el sistema c#, así que dime si esto tiene alguna solución y por dios no me digas que me cambie a c# jajajaja, que no me importaría pero esta gente lo está abandonando, bueno un saludo y espero que todo te vaya bien.

**Comment by PokeSer** [comment]
Hola @dkdue, no te preocupes, le echo un vistazo y te comento por aquí en cuanto tenga esto solucionado, gracias por el log!

**Comment by PokeSer** [comment]
Ya está solucionado todo con la última update, recuerda actulizar, gracias!
