### ISSUE TITLE
Existe alguna forma para REDEM?

### ISSUE THREAD

**Issue by zandercillo94** [PokeSerGG/poke_rpchat#3]
Hola! Existe alguna forma de usarlo en REDEM? 

Saludos!

**Comment by PokeSer** [comment]
Hola, buenas noches, el script es para RedM, pero solo para el soporte de VORP C#RE

**Comment by PokeSer** [comment]
Pero puedes convertirlo fácilmente

**Comment by JappIC** [comment]
Hello. Thank you very much for the script.

I have a question. When you send an alert, does it only reach the first doctor who connected to the server instead of all the doctors?

The same goes for the police.

**Comment by PokeSer** [comment]
Hi @JappIC, i have released an update that in theory fixes this. If you try it, tell me if it keeps failing please, thanks!
